### ISSUE TITLE
Status Code 400 when creating a new Repository 

### ISSUE THREAD

**Issue by andrevks** [wwsalmon/postulate#112]
I tried to create a new repository and this issue came up:

![Screenshot 2022-11-26 at 12 10 43](https://user-images.githubusercontent.com/39144691/204098125-31b81bcc-de40-4b55-a583-e908edcaa480.png)

Is there a way to contribute to the development of the project? I'm new to open-source LOL.

**Comment by wwsalmon** [comment]
fixed! projects can now be created with empty descriptions

**Comment by wwsalmon** [comment]
@andrevks thanks for opening the issue! problem was that there was an unhandled error when creating a project with the description field empty. refactored some code so that projects can now be created with empty descriptions

re: contributing, i'm not working on this super actively so there's not a *great* way at the moment -- if you're familiar with MongoDB, Google OAuth, etc. you can set up your own staging backend, clone this repo locally and do your own dev. If more people start to use Postulate or if you're really interested in something specific I can write up some documentation.
